feat: define common attributes type
open-telemetry/opentelemetry-js-api pull request #142
Opened 2021-12-16 18:49 UTC by dyladan

As discussed in SIG, this creates a common definition for attributes which can be used by all signals.

Span attributes is marked as deprecated in favor of the new common attributes definition.

2021-12-16 19:09 UTC, Flarna approved these changes

2021-12-16 19:09 UTC, Flarna commented on src/common/Attributes.ts
> +    | Array<null | undefined | boolean>;
add a newline at end of file

2021-12-16 19:12 UTC, dyladan commented on src/common/Attributes.ts
> +    | Array<null | undefined | boolean>;
There already is a newline. Github shows a red icon if the newline is missing

2021-12-16 19:12 UTC, mwear approved these changes
LGTM. Since we are marking `SpanAttributes` as deprecated, should we have a follow up task to replace usage with `Attributes`?

2021-12-17 07:55 UTC, pirgeo approved these changes

2021-12-17 09:21 UTC, legendecas commented on src/common/Attributes.ts
> +    | Array<null | undefined | string>
The spec says "`null` values SHOULD NOT be allowed in arrays".

> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attribute

2021-12-17 09:23 UTC, legendecas requested changes
Since there are already 2 approvals, mark the PR as changes requested to prevent accidental merging until we solve the questions.

2021-12-17 09:29 UTC, Flarna commented on src/common/Attributes.ts
> +    | Array<null | undefined | string>
Removing `null` here would be a breaking change.
As it is just a SHOULD an not a MUST statement I would consider it as ok because JS is one of the `languages that do not have appropriate compile-time type checking`).

2021-12-17 09:39 UTC, legendecas commented on src/common/Attributes.ts
> +    | Array<null | undefined | string>
JS can always disrespect these typescript notations. Here we are writing TypeScript which has a compile-time type checking, no?

2021-12-17 09:45 UTC, Flarna commented on src/common/Attributes.ts
> +    | Array<null | undefined | string>
Well, the repos are named opentelemetry-js not opentelemetry-ts so not sure if JavaScrit or TypeScript is the main target.

Not sure then if changes in type definition like this should be considered as breaking at all. I was assuming yes as there are a lot users out there which also use typescript and for them such a change could break their code.

Also the current Trace SDK handles `null` entries in arrays as far as I remember and it has also reached GA.

2021-12-17 09:48 UTC, legendecas approved these changes

2021-12-17 21:13 UTC, dyladan commented on src/common/Attributes.ts
> +    | Array<null | undefined | string>
I would consider any change that breaks the types to be a breaking change as a project which uses our project may work one day and fail to compile the next if they update. I took the types exactly as they were before unchanged for this reason.

2022-01-07 20:56 UTC, blumamir approved these changes

2022-01-08 15:04 UTC, vmarchaud approved these changes

2022-01-08 17:40 UTC, merged